version: "3.8"
services:
  dev_env:
    image: node
    environment:
      - CERT=${CERT}
      - KEY=${KEY}
      - CHAIN_CERT=${CHAIN_CERT}
    volumes:
      - "./:/src"
    working_dir: /src
    command:
      - npm
      - run
      - app